### PR TITLE
feat: Support upload of binary `files` parameter in generated pipeline APIs

### PR DESCRIPTION
**Pull request by asymness**
Resolves https://github.com/Unstructured-IO/community/issues/14

- [x] `pipeline_api` must have a file or text parameter (or both), otherwise an error is thrown by `unstructured_api_tools convert-pipeline-notebooks`. If `file` exists as a parameter in `pipeline_api`, the FastAPI route should accept `files` as parameter.
- [x] The new `pipeline_api` parameters are supported: `file`, `file_content_type`, and `filename`.
- [x] If a single file is specified in the request, the response is simply returned as the result from pipeline_api.
- [x] However, if multiple files are specified in the request, a multipart/mixed response should be constructed where each part is the result of a pipeline_api call.
- [x] Verify that the generated `pipeline-sec-filings` API continues to work as expected with plain text files.
- [x] The version in unstructured-api-tools is incremented to `0.4.1`.
- [x] Test notebook that generates an API that accepts uploads of PDF files and saves them to the project root directory with a JSON success message response: https://gist.github.com/asymness/cd4cbf27f6e60efa369b452e8340d024
- [x] Update unit tests

### CODE REVIEW

**Review by cragwolfe — CHANGES_REQUESTED** [review]
Apologies on the confusion on how to handle both `text` and `file` within a `pipeline_api` call. The idea is that only one not-`None` value would be passed to `pipeline_api` if it has a signature like:

    pipeline_api(text, file, ...)

Otherwise, looks really good!

**Comment by asymness** [comment]
Hi @cragwolfe, thanks for the clarification. I have made the requested changes to handle `text_files` and `files` parameters separately and also added another test. Please take a look when available. Thanks!

**Review by cragwolfe — APPROVED** [review]
One minor request: can the indentation of the `{ % if % }` statements in `pipeline_api.txt` for the large blocks related to ` {% if accepts_text and accepts_file %}` be indented differently to make it more clearly where those blocks begin and end? Probably OK if they are just fully left aligned, e.g. on line 115:

```
{% if accepts_text and accepts_file %}
    has_text = isinstance(text_files, list) and len(text_files)
    has_files = isinstance(files, list) and len(files)
```

Besides that, looks great! Verified locally and also tested mixed `text_files` and `files` case: https://gist.github.com/cragwolfe/f940d503ff5884c06831f9270ced42dd

**Comment by asymness** [comment]
@cragwolfe, thanks for pointing that out. I have fixed the indentation now.

**Pull request merged**
