### PR TITLE
CSV output formatting fix

### PR DESCRIPTION
**Pull request by rbiseck3**
If output type is text/csv, wrap in PlainTextResponse to maintain formatting

### CODE REVIEW

**Comment by rbiseck3** [comment]
Not sure what the best response formatting would be when there are multiple files that need csv outputs. Right now it still defaults to the `application/json` response type which wraps the strings into a json array.

**Comment by rbiseck3** [comment]
For multi file outputs, the csv content is joined with the others using an outer join so if there were different columns, they would all be persisted.

**Comment by rbiseck3** [comment]
Since the code in the `prepline_test_project` directory is autogenerated, I felt it didn't make sense to require a code coverage percentage here since it makes sense that there might be more code generated than needed for every case of wrapped code from a notebook. That directory was removed from the make target that runs pytest.

**Review by cragwolfe — CHANGES_REQUESTED** [review]
Hmm, not sure about skipping generated code completely from codecov completely.

At the end of the day, what really matters is the autogenerated code itself is performing as expected. In theory, it shouldn't be hard to trigger additional coverage https://github.com/Unstructured-IO/unstructured-api-tools/blob/main/test_unstructured_api_tools/api/test_file_apis.py (and test_file_text_apis.py, test_text_apis.txt)?

**Comment by awalker4** [comment]
I'm getting an error with `make tidy-notebooks`, which is going to execute all the cells. Is there a missing pandas import somewhere?
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 print(pipeline_api("some text", "text/csv", "isd"))

Cell In[1], line 7, in pipeline_api(text, response_type, response_schema)
      2 def pipeline_api(
      3     text,
      4     response_type="text/csv",
      5     response_schema="isd",
      6 ):
----> 7     data = pd.DataFrame(data={"silly_result": [str(len(text)), text, str(response_type), str(response_schema)]})
      8     if response_type == "text/csv":
      9         return data.to_csv()

NameError: name 'pd' is not defined
NameError: name 'pd' is not defined
```

**Review by cragwolfe — APPROVED** [review]

**Pull request merged**
